#Version of the ROM
TIPSY_CODENAME := T10x
TIPSY_REVISION := Affligem

ifndef TIPSY_BUILDTYPE
  TIPSY_BUILDTYPE := UNOFFICIAL
endif

TARGET_PRODUCT_SHORT := $(TARGET_PRODUCT)
TARGET_PRODUCT_SHORT := $(subst tipsy_,,$(TARGET_PRODUCT_SHORT))

TIPSY_VERSION := $(TIPSY_REVISION)-$(TIPSY_CODENAME)-$(TIPSY_BUILDTYPE)-$(TARGET_PRODUCT_SHORT)-$(shell date -u +%Y%m%d-%H%M)

PRODUCT_BUILD_PROP_OVERRIDES += BUILD_DISPLAY_ID="$(BUILD_ID)-$(BUILD_USERNAME)@$(BUILD_HOSTNAME)"
